version: '3'

services:

  mysql:
    container_name: 'node-mysql'
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"

  flask:
    container_name: 'node-flask'
    build: .
    ports:
      - "5000:5000"
    links:
        - mysql
    depends_on:
        - mysql
  redis:
    container_name: 'node-redis'
    image: 'redis:5.0.3'
    ports:
      - '6379:6379'
  nginx:
    container_name: 'node-nginx'
    image: "nginx:1.13.5"
    ports:
      - "80:80"
    links:
        - flask
    depends_on:
        - flask
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
