version: '3'

services:

  mysql:
    container_name: 'dev-node-mysql'
    image: "mysql:5.7"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"

  redis:
    container_name: 'dev-node-redis'
    image: 'redis:5.0.3'
    ports:
      - '6379:6379'
